Repository Quansight-Labs/accessible-pygments, pull requests merged in 2024-03, with the labels that each got.

#39 [DOC] Remove conda instructions from contributing
  CONTRIBUTING.md
  README.md
Labels: area: documentation 📖

#42 Automate theme READMEs
  CONTRIBUTING.md
  a11y_pygments/a11y_dark/README.md
  a11y_pygments/a11y_dark/style.py
  a11y_pygments/a11y_high_contrast_dark/README.md
  a11y_pygments/a11y_high_contrast_light/README.md
  a11y_pygments/a11y_light/README.md
  a11y_pygments/blinds_dark/README.md
  a11y_pygments/blinds_light/README.md
  a11y_pygments/github_dark/README.md
  a11y_pygments/github_dark_colorblind/README.md
  a11y_pygments/github_dark_high_contrast/README.md
  a11y_pygments/github_dark_high_contrast/images/github-dark-high-contrast.png
  a11y_pygments/github_light/README.md
  a11y_pygments/github_light_colorblind/README.md
  a11y_pygments/github_light_high_contrast/README.md
  a11y_pygments/github_light_high_contrast/images/github-light-high-contrast.png
  a11y_pygments/gotthard_dark/README.md
  a11y_pygments/gotthard_light/README.md
  a11y_pygments/greative/README.md
  a11y_pygments/pitaya_smoothie/README.md
  a11y_pygments/utils/utils.py
  a11y_pygments/utils/wcag_contrast.py
  docs/index.html
  pyproject.toml
  scripts/templates/theme_readme.md
  scripts/update_theme_docs.py
Labels: type: enhancement 💅🏼

#48 BUG - Ensure no local version
  pyproject.toml
Labels: type: bug 🐛

#43 Automate theme README screenshots
  CONTRIBUTING.md
  a11y_pygments/a11y_dark/images/a11y-dark.png
  a11y_pygments/a11y_high_contrast_dark/images/a11y-high-contrast-dark.png
  a11y_pygments/a11y_high_contrast_light/images/a11y-high-contrast-light.png
  a11y_pygments/a11y_light/images/a11y-light.png
  a11y_pygments/blinds_dark/images/blinds-dark.png
  a11y_pygments/blinds_light/images/blinds-light.png
  a11y_pygments/github_dark/images/github-dark.png
  a11y_pygments/github_dark_colorblind/images/github-dark-colorblind.png
  a11y_pygments/github_dark_high_contrast/images/github-dark-high-contrast.png
  a11y_pygments/github_light/images/github-light.png
  a11y_pygments/github_light_colorblind/images/github-light-colorblind.png
  a11y_pygments/github_light_high_contrast/images/github-light-high-contrast.png
  a11y_pygments/gotthard_dark/images/gotthard-dark.png
  a11y_pygments/gotthard_light/images/gotthard-light.png
  a11y_pygments/greative/images/greative.png
  a11y_pygments/pitaya_smoothie/images/pitaya-smoothie.png
  pyproject.toml
  scripts/update_theme_docs.py
Labels: type: enhancement 💅🏼

#45 MAINT - Update pre-commit hooks
  .pre-commit-config.yaml
  CONTRIBUTING.md
  a11y_pygments/__init__.py
  a11y_pygments/utils/utils.py
  a11y_pygments/utils/wcag_contrast.py
  docs/index.html
  pyproject.toml
  scripts/update_theme_docs.py
  test/render_html.py
  test/run_css.py
  test/scripts/test.html
  test/test_contrast.py
Labels: type: maintenance 🛠, status: needs review 👀, do-not-merge
